### ISSUE TITLE
Track Loading Failed

### ISSUE THREAD

**Issue by hydrox19** [Topis-Lavalink-Plugins/Topis-Source-Managers-Plugin#9]
Stack Trace: 
```java
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:236)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:225)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:830)
java.lang.RuntimeException: com.github.topislavalinkplugins.topissourcemanagers.applemusic.AppleMusicWebAPIException: Not Found
    at com.github.topislavalinkplugins.topissourcemanagers.applemusic.AppleMusicSourceManager.loadItem(AppleMusicSourceManager.java:62)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:830)
com.github.topislavalinkplugins.topissourcemanagers.applemusic..AppleMusicWebAPIException: Not Found
    at com.github.topislavalinkplugins.topissourcemanagers.applemusic.AppleMusicClient.request(AppleMusicClient.java:131)
    at com.github.topislavalinkplugins.topissourcemanagers.applemusic.AppleMusicClient.getClass(AppleMusicClient.java:109)
    at com.github.topislavalinkplugins.topissourcemanagers.applemusic.AppleMusicClient.getPlaylist(AppleMusicClient.java:92)
    at com.github.topislavalinkplugins.topissourcemanagers.applemusic.AppleMusicSourceManager.getPlaylist(AppleMusicSourceManager.java:112)
    at com.github.topislavalinkplugins.topissourcemanagers.applemusic.AppleMusicSourceManager.loadItem(AppleMusicSourceManager.java:55)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:830)
```

**Comment by txj-xyz** [comment]
HI, can you please try this again with the latest release?

If this works, please close the issue.

If not, please post the full URL you are attempting to use and the stack trace as you've already posted above

**Comment by txj-xyz** [comment]
@hydrox19

**Comment by txj-xyz** [comment]
@TopiSenpai Please close
